/**
 * Serialization Fixture Tests
 *
 * These tests compare our TypeScript DhtOp serialization against
 * known-good byte fixtures generated by Holochain's Rust implementation.
 *
 * CRITICAL: These tests use the ACTUAL code paths from the extension,
 * not hand-crafted test data. This ensures we test what actually runs.
 *
 * The fixtures are generated by: hc-http-gw-fork/tests/serialization_fixtures.rs
 * Run with: cargo test --test serialization_fixtures -- --nocapture
 */

import { describe, it, expect } from "vitest";
import { hashFrom32AndType, HoloHashType, ActionType } from "@holochain/client";
import type {
  Action,
  Create,
  Delete,
  CreateLink,
  Entry,
  Record as HolochainRecord,
  SignedActionHashed,
  ActionHashed,
  Signature,
  NewEntryAction,
} from "@holochain/client";

// Import the ACTUAL code paths used by the extension
import {
  produceOpsFromRecord,
  serializeOpForGateway,
  ChainOpType,
} from "../src/dht";

// ============================================================================
// Known-Good Fixtures from Rust (holochain_serialized_bytes)
// ============================================================================

// These are base64-encoded msgpack bytes generated by:
// cargo test --test serialization_fixtures -- --nocapture

const RUST_FIXTURES = {
  // RegisterAgentActivity with Create action
  // Action enum is INTERNALLY tagged: { "type": "Create", author, ... }
  RegisterAgentActivity: "gadDaGFpbk9wgbVSZWdpc3RlckFnZW50QWN0aXZpdHmSxECqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqiKR0eXBlpkNyZWF0ZaZhdXRob3LEJ4QgJBERERERERERERERERERERERERERERERERERERERERER/UGvt6l0aW1lc3RhbXDPAAYN1xAhIACqYWN0aW9uX3NlcQWrcHJldl9hY3Rpb27EJ4QpJCIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIivhNJZKplbnRyeV90eXBlgaNBcHCDq2VudHJ5X2luZGV4AKp6b21lX2luZGV4AKp2aXNpYmlsaXR5plB1YmxpY6plbnRyeV9oYXNoxCeEISQzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzM9sC1F+md2VpZ2h0g6lidWNrZXRfaWQApXVuaXRzAKpyYXRlX2J5dGVzAA==",

  // StoreRecord with Create action
  // Action enum is INTERNALLY tagged: { "type": "Create", author, ... }
  StoreRecord: "gadDaGFpbk9wgatTdG9yZVJlY29yZJPEQKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqIpHR5cGWmQ3JlYXRlpmF1dGhvcsQnhCAkERERERERERERERERERERERERERERERERERERERERERH9Qa+3qXRpbWVzdGFtcM8ABg3XECEgAKphY3Rpb25fc2VxBatwcmV2X2FjdGlvbsQnhCkkIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiK+E0lkqmVudHJ5X3R5cGWBo0FwcIOrZW50cnlfaW5kZXgAqnpvbWVfaW5kZXgAqnZpc2liaWxpdHmmUHVibGljqmVudHJ5X2hhc2jEJ4QhJDMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz2wLUX6Z3ZWlnaHSDqWJ1Y2tldF9pZACldW5pdHMAqnJhdGVfYnl0ZXMAgadQcmVzZW50gqplbnRyeV90eXBlo0FwcKVlbnRyecQFAQIDBAU=",

  // StoreEntry with Create action
  // NewEntryAction enum is EXTERNALLY tagged: { "Create": { author, ... } }
  // Note: 7 fields in the action (no "type" field), wrapped in "Create" key
  StoreEntry: "gadDaGFpbk9wgapTdG9yZUVudHJ5k8RAqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqoGmQ3JlYXRlh6ZhdXRob3LEJ4QgJBERERERERERERERERERERERERERERERERERERERERER/UGvt6l0aW1lc3RhbXDPAAYN1xAhIACqYWN0aW9uX3NlcQWrcHJldl9hY3Rpb27EJ4QpJCIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIivhNJZKplbnRyeV90eXBlgaNBcHCDq2VudHJ5X2luZGV4AKp6b21lX2luZGV4AKp2aXNpYmlsaXR5plB1YmxpY6plbnRyeV9oYXNoxCeEISQzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzM9sC1F+md2VpZ2h0g6lidWNrZXRfaWQApXVuaXRzAKpyYXRlX2J5dGVzAIKqZW50cnlfdHlwZaNBcHClZW50cnnEBQECAwQF",

  // RegisterAddLink with CreateLink action
  // CreateLink struct (no type field) - raw struct, not Action enum
  RegisterAddLink: "gadDaGFpbk9wga9SZWdpc3RlckFkZExpbmuSxECqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqiqZhdXRob3LEJ4QgJBERERERERERERERERERERERERERERERERERERERERER/UGvt6l0aW1lc3RhbXDPAAYN1xAhIACqYWN0aW9uX3NlcQircHJldl9hY3Rpb27EJ4QpJCIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIivhNJZKxiYXNlX2FkZHJlc3PEJ4QhJDMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz2wLUX650YXJnZXRfYWRkcmVzc8QnhCEkRERERERERERERERERERERERERERERERERERERERERER7z3URqnpvbWVfaW5kZXgAqWxpbmtfdHlwZQCjdGFnxAMBAgOmd2VpZ2h0gqlidWNrZXRfaWQApXVuaXRzAA==",

  // RegisterDeletedBy with Delete action
  // Delete struct (no type field) - raw struct, not Action enum
  RegisterDeletedBy: "gadDaGFpbk9wgbFSZWdpc3RlckRlbGV0ZWRCeZLEQKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqHpmF1dGhvcsQnhCAkERERERERERERERERERERERERERERERERERERERERERH9Qa+3qXRpbWVzdGFtcM8ABg3XECEgAKphY3Rpb25fc2VxB6twcmV2X2FjdGlvbsQnhCkkIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiK+E0lkr2RlbGV0ZXNfYWRkcmVzc8QnhCkkRERERERERERERERERERERERERERERERERERERERERER7z3URtWRlbGV0ZXNfZW50cnlfYWRkcmVzc8QnhCEkVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWdqlgdpndlaWdodIKpYnVja2V0X2lkAKV1bml0cwA=",
};

// ============================================================================
// Test Data Builders (matching Rust test fixtures)
// These use the exact same values as the Rust tests
// ============================================================================

/** Create deterministic 32-byte hash core */
function makeHash32(seed: number): Uint8Array {
  return new Uint8Array(32).fill(seed);
}

/** Create 39-byte AgentPubKey with proper prefix */
function makeAgentPubKey(seed: number): Uint8Array {
  return hashFrom32AndType(makeHash32(seed), HoloHashType.Agent);
}

/** Create 39-byte ActionHash with proper prefix */
function makeActionHash(seed: number): Uint8Array {
  return hashFrom32AndType(makeHash32(seed), HoloHashType.Action);
}

/** Create 39-byte EntryHash with proper prefix */
function makeEntryHash(seed: number): Uint8Array {
  return hashFrom32AndType(makeHash32(seed), HoloHashType.Entry);
}

/** Create 64-byte signature (all 0xaa to match Rust) */
function makeSignature(): Signature {
  return new Uint8Array(64).fill(0xaa) as Signature;
}

/** Fixed timestamp matching Rust: 2024-01-01 00:00:00 UTC in microseconds */
const FIXED_TIMESTAMP = 1704067200000000;

// ============================================================================
// Action Builders - Create actions matching @holochain/client types
// These are the exact format that storedActionToClientAction produces
// ============================================================================

/**
 * Create a Create action in the exact format that the extension produces.
 * This matches what storedActionToClientAction() outputs.
 */
function makeCreateAction(): Create {
  return {
    type: ActionType.Create,
    author: makeAgentPubKey(0x11),
    timestamp: FIXED_TIMESTAMP,
    action_seq: 5,
    prev_action: makeActionHash(0x22),
    entry_type: { App: { entry_index: 0, zome_index: 0, visibility: "Public" } },
    entry_hash: makeEntryHash(0x33),
    weight: { bucket_id: 0, units: 0, rate_bytes: 0 },
  } as Create;
}

/**
 * Create a Delete action in the exact format that the extension produces.
 */
function makeDeleteAction(): Delete {
  return {
    type: ActionType.Delete,
    author: makeAgentPubKey(0x11),
    timestamp: FIXED_TIMESTAMP,
    action_seq: 7,
    prev_action: makeActionHash(0x22),
    deletes_address: makeActionHash(0x44),
    deletes_entry_address: makeEntryHash(0x55),
    weight: { bucket_id: 0, units: 0 },
  } as Delete;
}

/**
 * Create a CreateLink action in the exact format that the extension produces.
 */
function makeCreateLinkAction(): CreateLink {
  return {
    type: ActionType.CreateLink,
    author: makeAgentPubKey(0x11),
    timestamp: FIXED_TIMESTAMP,
    action_seq: 8,
    prev_action: makeActionHash(0x22),
    base_address: makeEntryHash(0x33),
    target_address: makeEntryHash(0x44),
    zome_index: 0,
    link_type: 0,
    tag: new Uint8Array([0x01, 0x02, 0x03]),
    weight: { bucket_id: 0, units: 0 },
  } as CreateLink;
}

// ============================================================================
// Record Builders - Build Records like buildRecord() does
// ============================================================================

/**
 * Build a Record in the exact format that buildRecord() produces.
 * This is what gets passed to produceOpsFromRecord().
 */
function buildTestRecord(action: Action, entry?: Entry): HolochainRecord {
  const actionHashed: ActionHashed = {
    hash: makeActionHash(0xaa), // Dummy hash for testing
    content: action,
  };

  const signedActionHashed: SignedActionHashed = {
    hashed: actionHashed,
    signature: makeSignature(),
  };

  const recordEntry = entry
    ? { Present: entry }
    : { NotApplicable: undefined as void };

  return {
    signed_action: signedActionHashed,
    entry: recordEntry,
  };
}

// ============================================================================
// Comparison Utilities
// ============================================================================

function base64ToBytes(base64: string): Uint8Array {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function compareBytes(name: string, actual: Uint8Array, expected: Uint8Array): void {
  console.log(`\n=== Comparing: ${name} ===`);
  console.log(`Actual length: ${actual.length}, Expected length: ${expected.length}`);

  if (actual.length !== expected.length) {
    console.log(`LENGTH MISMATCH!`);
  }

  // Find first difference
  const minLen = Math.min(actual.length, expected.length);
  for (let i = 0; i < minLen; i++) {
    if (actual[i] !== expected[i]) {
      console.log(`FIRST DIFF at byte ${i}: actual=0x${actual[i].toString(16).padStart(2, "0")}, expected=0x${expected[i].toString(16).padStart(2, "0")}`);

      // Print context
      const start = Math.max(0, i - 10);
      const end = Math.min(minLen, i + 20);
      console.log(`Actual   [${start}-${end}]: ${bytesToHex(actual.slice(start, end))}`);
      console.log(`Expected [${start}-${end}]: ${bytesToHex(expected.slice(start, end))}`);
      break;
    }
  }

  if (actual.length === expected.length && bytesToHex(actual) === bytesToHex(expected)) {
    console.log("MATCH: Bytes are identical!");
  }
}

// ============================================================================
// Tests - Using ACTUAL code paths from the extension
// ============================================================================

describe("Serialization Fixtures (Actual Code Paths)", () => {
  describe("RegisterAgentActivity", () => {
    it("should match Rust fixture when using produceOpsFromRecord", () => {
      // Build a Record like buildRecord() does
      const entry: Entry = { entry_type: "App", entry: new Uint8Array([1, 2, 3, 4, 5]) };
      const record = buildTestRecord(makeCreateAction(), entry);

      // Use the ACTUAL produceOpsFromRecord function
      const ops = produceOpsFromRecord(record);

      // Find the RegisterAgentActivity op
      const regActivityOp = ops.find(op => op.type === ChainOpType.RegisterAgentActivity);
      expect(regActivityOp).toBeDefined();

      // Serialize using the ACTUAL serializeOpForGateway function
      const actual = serializeOpForGateway(regActivityOp!);
      const expected = base64ToBytes(RUST_FIXTURES.RegisterAgentActivity);

      compareBytes("RegisterAgentActivity", actual, expected);
      expect(actual).toEqual(expected);
    });
  });

  describe("StoreRecord", () => {
    it("should match Rust fixture when using produceOpsFromRecord", () => {
      const entry: Entry = { entry_type: "App", entry: new Uint8Array([1, 2, 3, 4, 5]) };
      const record = buildTestRecord(makeCreateAction(), entry);

      const ops = produceOpsFromRecord(record);

      // Find the StoreRecord op
      const storeRecordOp = ops.find(op => op.type === ChainOpType.StoreRecord);
      expect(storeRecordOp).toBeDefined();

      const actual = serializeOpForGateway(storeRecordOp!);
      const expected = base64ToBytes(RUST_FIXTURES.StoreRecord);

      compareBytes("StoreRecord", actual, expected);
      expect(actual).toEqual(expected);
    });
  });

  describe("StoreEntry", () => {
    it("should match Rust fixture when using produceOpsFromRecord", () => {
      // StoreEntry requires an entry
      const entry: Entry = { entry_type: "App", entry: new Uint8Array([1, 2, 3, 4, 5]) };
      const record = buildTestRecord(makeCreateAction(), entry);

      const ops = produceOpsFromRecord(record);

      // Find the StoreEntry op
      const storeEntryOp = ops.find(op => op.type === ChainOpType.StoreEntry);
      expect(storeEntryOp).toBeDefined();

      const actual = serializeOpForGateway(storeEntryOp!);
      const expected = base64ToBytes(RUST_FIXTURES.StoreEntry);

      compareBytes("StoreEntry", actual, expected);
      expect(actual).toEqual(expected);
    });
  });

  describe("RegisterAddLink", () => {
    it("should match Rust fixture when using produceOpsFromRecord", () => {
      // CreateLink doesn't have an entry
      const record = buildTestRecord(makeCreateLinkAction() as Action);

      const ops = produceOpsFromRecord(record);

      // Find the RegisterAddLink op
      const regAddLinkOp = ops.find(op => op.type === ChainOpType.RegisterAddLink);
      expect(regAddLinkOp).toBeDefined();

      const actual = serializeOpForGateway(regAddLinkOp!);
      const expected = base64ToBytes(RUST_FIXTURES.RegisterAddLink);

      compareBytes("RegisterAddLink", actual, expected);
      expect(actual).toEqual(expected);
    });
  });

  describe("RegisterDeletedBy", () => {
    it("should match Rust fixture when using produceOpsFromRecord", () => {
      // Delete doesn't have an entry
      const record = buildTestRecord(makeDeleteAction() as Action);

      const ops = produceOpsFromRecord(record);

      // Find the RegisterDeletedBy op
      const regDeletedByOp = ops.find(op => op.type === ChainOpType.RegisterDeletedBy);
      expect(regDeletedByOp).toBeDefined();

      const actual = serializeOpForGateway(regDeletedByOp!);
      const expected = base64ToBytes(RUST_FIXTURES.RegisterDeletedBy);

      compareBytes("RegisterDeletedBy", actual, expected);
      expect(actual).toEqual(expected);
    });
  });
});
