/**
 * Utilities for constructing StoredKeyEntry from raw seed bytes.
 *
 * Used when loading keys from external sources (files, env vars, hex strings)
 * rather than generating them via LairClient.newSeed().
 */

import sodium from "libsodium-wrappers";
import type { EntryTag, StoredKeyEntry } from "./types";

/**
 * Runtime guard — narrows libsodium's string | Uint8Array return to Uint8Array.
 */
function asBytes(value: string | Uint8Array): Uint8Array {
  if (value instanceof Uint8Array) return value;
  throw new Error("Expected Uint8Array from libsodium, got string");
}

/**
 * Construct a full StoredKeyEntry from a 32-byte ed25519 seed.
 *
 * Derives the ed25519 keypair and x25519 public key using libsodium,
 * mirroring the internal logic of LairClient.importSeed() and deriveSeed().
 *
 * Note: StoredKeyEntry.seed stores the 64-byte libsodium private key
 * (not the original 32-byte seed). This matches how LairClient.newSeed()
 * stores keys.
 *
 * @param seed - 32-byte ed25519 seed
 * @param tag - Unique tag for this entry
 * @param exportable - Whether this key can be exported (default: false)
 */
export async function seedToStoredEntry(
  seed: Uint8Array,
  tag: EntryTag,
  exportable = false,
): Promise<StoredKeyEntry> {
  if (seed.length !== 32) {
    throw new Error(`Expected 32-byte seed, got ${seed.length} bytes`);
  }

  await sodium.ready;

  const keypair = sodium.crypto_sign_seed_keypair(seed);
  const publicKey = asBytes(keypair.publicKey);
  const privateKey = asBytes(keypair.privateKey);

  const x25519PubKey = asBytes(
    sodium.crypto_sign_ed25519_pk_to_curve25519(publicKey),
  );

  return {
    info: {
      tag,
      ed25519_pub_key: publicKey,
      x25519_pub_key: x25519PubKey,
      created_at: Date.now(),
      exportable,
    },
    seed: privateKey,
  };
}

/**
 * Parse a hex-encoded string into a Uint8Array seed.
 *
 * Accepts hex strings with or without whitespace/newlines
 * (e.g., from key files generated by `head -c 32 /dev/urandom | xxd -p`).
 *
 * @param hex - Hex-encoded string (64 hex chars = 32 bytes)
 */
export function hexToSeed(hex: string): Uint8Array {
  const cleaned = hex.replace(/\s+/g, "");
  if (cleaned.length !== 64) {
    throw new Error(
      `Expected 64 hex characters (32 bytes), got ${cleaned.length}`,
    );
  }
  const bytes = new Uint8Array(32);
  for (let i = 0; i < 32; i++) {
    bytes[i] = parseInt(cleaned.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}
